# Shared, agent-agnostic helpers for the agentless hook library (POSIX sh).
#
# Composed with a per-agent file (claude.sh / copilot.sh) to form a deployed hook library:
# shared.sh + the agent file. For Claude that composition is embedded into
# claude-code.template.json as env.BB_LIB; for Copilot it is inlined into hooks.json.
# The deployed artifacts are GENERATED by build scripts — never edit them by hand.
#
# Hard constraint: a fresh machine is assumed to have ONLY the hook shell (sh on macOS/Linux,
# Git Bash on Windows), git, and curl. We never assume jq, node, python, or uuidgen exist, and
# we validate every external tool before use. node/jq are used ONLY for the best-effort
# transcript-derived LLMResponse/LLMThinking events, and only when detected.
#
# Behavior mirrors the prior jq hooks (see DEN-2746). POSIX sh only — no bashisms, no `local`.

# --- helpers -------------------------------------------------------------------------------

# RFC4122-v4 UUID without depending on uuidgen: prefer uuidgen, then /proc, then /dev/urandom.
bluebear_uuid() {
  BB_U=''
  if command -v uuidgen >/dev/null 2>&1; then
    BB_U=$(uuidgen | tr 'A-F' 'a-f')
  elif [ -r /proc/sys/kernel/random/uuid ]; then
    BB_U=$(cat /proc/sys/kernel/random/uuid)
  elif [ -r /dev/urandom ] && command -v od >/dev/null 2>&1; then
    BB_U=$(od -An -tx1 -N16 /dev/urandom | tr -d ' \n' \
      | sed -E 's/^(.{8})(.{4}).(.{3}).(.{3})(.{12}).*/\1-\2-4\3-8\4-\5/')
  fi
  # No UUID source available — surface it (fail loud) rather than emit an empty id silently.
  [ -z "$BB_U" ] && echo '[bluebear] bluebear_uuid: no UUID source (uuidgen/proc/urandom) available' >&2
  printf '%s' "$BB_U"
}

# JSON string escaping for the single-line scalars we inject. Escapes backslash and quote, plus
# tab and CR — a control char in a server deny reason would otherwise produce unparseable deny
# JSON, which Claude Code treats as "no decision" and lets the tool call through (fail-open).
# Every value reaches here single-line (the `[^"]*` field extraction can't cross newlines, and
# JSON encodes any real newline as the two chars \n), so a raw newline never occurs. tab/CR are
# matched as literal bytes, portable across BSD and GNU sed. Backslash is escaped first so the
# escape sequences introduced afterwards are not double-escaped.
bluebear_json_escape() {
  BB_TAB=$(printf '\t')
  BB_CR=$(printf '\r')
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e "s/$BB_TAB/\\\\t/g" -e "s/$BB_CR/\\\\r/g"
}

# A JSON value: quoted-escaped string, or literal null when empty.
bluebear_json_value() { if [ -z "$1" ]; then printf 'null'; else printf '"%s"' "$(bluebear_json_escape "$1")"; fi; }

# First top-level "field":"value" string out of the event (best-effort, no JSON parser).
bluebear_field() {
  printf '%s' "$BB_EVENT" \
    | sed -n 's/.*"'"$1"'"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n1
}

# POST a JSON body to the agentless endpoint; echoes the response. No-op (rc 1) without curl.
bluebear_post() {
  command -v curl >/dev/null 2>&1 || return 1
  printf '%s' "$1" | curl -s --max-time "$2" \
    -X POST "$BLUEBEAR_INGEST_URL/api/v1/events/agentless" \
    -H 'Content-Type: application/json' -d @- 2>/dev/null
}

# True when the local Bluebear handler daemon is up — then the handler owns capture.
bluebear_handler_running() {
  BB_RT="$HOME/.bluebear/runtime.json"
  [ -r "$BB_RT" ] || return 1
  BB_PORT=$(sed -n 's/.*"port"[[:space:]]*:[[:space:]]*"\{0,1\}\([0-9][0-9]*\).*/\1/p' "$BB_RT" | head -n1)
  [ -n "$BB_PORT" ] || return 1
  command -v curl >/dev/null 2>&1 || return 1
  curl -sf -m 1 -o /dev/null "http://127.0.0.1:$BB_PORT/status" 2>/dev/null
}

# Developer email: Claude oauth account, else git config.
bluebear_dev_email() {
  BB_EM=''
  BB_CJ="$HOME/.claude.json"
  [ -r "$BB_CJ" ] && BB_EM=$(sed -n 's/.*"emailAddress"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$BB_CJ" | head -n1)
  if [ -z "$BB_EM" ] && command -v git >/dev/null 2>&1; then
    BB_EM=$(git config ${1:+-C "$1"} user.email 2>/dev/null)
  fi
  printf '%s' "$BB_EM"
}

# Prompt-id state (shared by every agent): mint on UserPromptSubmit, cache per session,
# read it back on later hooks so a tool call correlates to its prompt. Sets BB_PID.
# Uses BB_SID (already set by the caller).
bluebear_prompt_id() {
  BB_SDIR="$HOME/.bluebear-agentless"
  mkdir -p "$BB_SDIR" 2>/dev/null
  # Sanitize session_id before putting it in a path — it comes from the event JSON, so strip
  # anything that isn't a safe filename char to prevent a `/` or `..` escaping the cache dir.
  BB_SID_SAFE=$(printf '%s' "$BB_SID" | tr -dc 'A-Za-z0-9_-')
  BB_PF="$BB_SDIR/${BB_SID_SAFE:-nosession}.prompt"
  if [ "$1" = "UserPromptSubmit" ]; then
    BB_PID=$(bluebear_uuid)
    [ -n "$BB_SID" ] && printf '%s' "$BB_PID" >"$BB_PF" 2>/dev/null
  else
    BB_PID=$(cat "$BB_PF" 2>/dev/null)
  fi
}

# Git context (shared) from working dir $1. Sets BB_GB (branch), BB_GROOT (repo path),
# BB_GREMOTE (origin url), and BB_GR (repo NAME — the Claude `git_repo_root` value).
bluebear_git() {
  BB_GB=''; BB_GROOT=''; BB_GREMOTE=''; BB_GR=''
  [ -n "$1" ] || return 0
  command -v git >/dev/null 2>&1 || return 0
  BB_GB=$(git -C "$1" rev-parse --abbrev-ref HEAD 2>/dev/null)
  BB_GROOT=$(git -C "$1" rev-parse --show-toplevel 2>/dev/null)
  BB_GREMOTE=$(git -C "$1" remote get-url origin 2>/dev/null)
  BB_GR=$(printf '%s' "$BB_GREMOTE" | sed -E -e 's#/+$##' -e 's#\.git$##' -e 's#.*[/:]##')
}

# Shared per-session identity+git cache (AGENT-AGNOSTIC) — avoid re-running the login/git/config
# IO on EVERY tool call. Sets BB_LOGIN, BB_DEV, BB_GB, BB_GR. login + developer_email are stable
# per session (resolved once); git branch/repo re-resolve only when cwd changes. The login SOURCE
# is agent-specific, so the dispatcher passes its resolver fn by name (Copilot: copilot_gh_login;
# Codex/etc. pass their own). State lives next to the prompt-id file. $1 = cwd, $2 = login-resolver fn.
bluebear_session_ctx() {
  BB_CTX="$BB_SDIR/${BB_SID_SAFE:-nosession}.ctx"
  BB_LOGIN=''; BB_DEV=''; BB_GB=''; BB_GR=''; BB_C_CWD=''
  if [ -r "$BB_CTX" ]; then
    BB_LOGIN=$(sed -n 's/^login=//p' "$BB_CTX" | head -n1)
    BB_DEV=$(sed -n 's/^email=//p' "$BB_CTX" | head -n1)
    BB_C_CWD=$(sed -n 's/^cwd=//p' "$BB_CTX" | head -n1)
    BB_GB=$(sed -n 's/^branch=//p' "$BB_CTX" | head -n1)
    BB_GR=$(sed -n 's/^repo=//p' "$BB_CTX" | head -n1)
  fi
  [ -z "$BB_LOGIN" ] && BB_LOGIN=$("$2")
  [ -z "$BB_DEV" ] && BB_DEV=$(bluebear_dev_email "$1")
  [ "$BB_C_CWD" != "$1" ] && bluebear_git "$1"   # bluebear_git sets BB_GB, BB_GR
  printf 'login=%s\nemail=%s\ncwd=%s\nbranch=%s\nrepo=%s\n' \
    "$BB_LOGIN" "$BB_DEV" "$1" "$BB_GB" "$BB_GR" >"$BB_CTX" 2>/dev/null
}

# Shared enrichment: append caller-provided fields to the RAW hook event, preserving EVERY
# original field (prompt, tool response, etc.) so downstream monitoring/naming is identical
# across agents. $1 = fields WITHOUT the wrapping braces. Used by every agent dispatcher
# (Copilot's copilot_main today; Codex/other global-settings agents reuse this same code).
bluebear_merge_event() {
  BB_TRIM=$(printf '%s' "$BB_EVENT" | sed -e 's/[[:space:]]*$//')
  printf '%s,%s}' "${BB_TRIM%\}}" "$1"
}
